<?php

namespace App\Models;

/*
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * THIS FILE IS AUTO-GENERATED BY AUTOMODEL:TABLE COMMAND
 * ANY CHANGES MADE TO THIS FILE MAY BE LOST
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 */

use Illuminate\Database\Eloquent\Model;

/**
 * No description found in the table comment.
 *
 * Class Jadwal
 * @package App\Models
 *
 * @property integer $id
 * @property integer $id_kelas
 * @property integer $id_pengajar
 * @property string $hari
 * @property integer $jam
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @property \App\Models\Absen[] $absens
 * @property \App\Models\Kelas $kelas
 * @property \App\Models\Pengajar $pengajar
 */
class Jadwal extends Model
{

	/**
	 * The table associated with the model.
	 *
	 * @var string
	 */
	protected $table = 'jadwal';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id_kelas', 'id_guru','id_pelajaran', 'hari', 'jam',
    ];

    /**
	 * The attributes that should be hidden for arrays.
	 *
	 * @var array
	 */
	protected $hidden = ['pivot'];


	/**
	 * The attributes appended to the model's JSON form.
	 *
	 * @var array
	 */
	protected $appends = [];

	/**
	 * The attributes that should be mutated to dates.
	 *
	 * @var array
	 */
	protected $dates = ['created_at', 'updated_at'];



	/**
	 * @return \Illuminate\Database\Eloquent\Relations\HasMany
	 */
	public function absens()
	{
		return $this->hasMany(
			// Model
			'App\Models\Absen',
			// Foreign key
			'id_jadwal',
			// Local key
			'id'
		);
	}

	/**
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
	 */
	public function kela()
	{
		return $this->belongsTo(
			// Model
			'App\Models\Kela',
			// Foreign key
			'id',
			// Other key
			'id_kelas'
		);
	}

	/**
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
	 */
	public function pengajar()
	{
		return $this->belongsTo(
			// Model
			'App\Models\Pengajar',
			// Foreign key
			'id',
			// Other key
			'id_pengajar'
		);
	}

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function jam()
    {
        return $this->belongsTo(
        // Model
            'App\Models\Jam',
            // Foreign key
            'id',
            // Other key
            'jam'
        );
    }

}
