<?php

namespace App\Models;

/*
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * THIS FILE IS AUTO-GENERATED BY AUTOMODEL:TABLE COMMAND
 * ANY CHANGES MADE TO THIS FILE MAY BE LOST
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 */
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Zizaco\Entrust\Traits\EntrustUserTrait;

/**
 * No description found in the table comment.
 *
 * Class User
 * @package App\Models
 *
 * @property integer $id
 * @property string $name
 * @property string $password
 * @property string $token_first_login
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @property \App\Models\Absence[] $absences
 * @property \App\Models\DetailStudent[] $detailStudents
 * @property \App\Models\Role[] $roles
 * @property \App\Models\Schedule[] $schedules
 */
class User extends Authenticatable
{
    use Notifiable;
    use EntrustUserTrait;
	/**
	 * The table associated with the model.
	 *
	 * @var string
	 */
	protected $table = 'users';


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'name','password','token_first_login',
    ];


    /**
	 * The attributes that should be hidden for arrays.
	 *
	 * @var array
	 */
    protected $hidden = [
        'password', 'token_first_login',
    ];


	/**
	 * The attributes appended to the model's JSON form.
	 *
	 * @var array
	 */
	protected $appends = [];

	/**
	 * The attributes that should be mutated to dates.
	 *
	 * @var array
	 */
	protected $dates = ['created_at', 'updated_at'];



	/**
	 * @return \Illuminate\Database\Eloquent\Relations\HasMany
	 */
	public function absences()
	{
		return $this->hasMany(
			// Model
			'App\Models\Absence',
			// Foreign key
			'student_id',
			// Local key
			'id'
		);
	}

	/**
	 * @return \Illuminate\Database\Eloquent\Relations\HasMany
	 */
	public function detailStudents()
	{
		return $this->hasMany(
			// Model
			'App\Models\DetailStudent',
			// Foreign key
			'student_id',
			// Local key
			'id'
		);
	}

	/**
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
	 */
	public function roles()
	{
		return $this->belongsToMany(
			// Model
			'App\Models\Role',
			// Pivot table
			'role_user',
			// "Our" key
			'user_id',
			// "Their" key
			'role_id'
		);
	}

	/**
	 * @return \Illuminate\Database\Eloquent\Relations\HasMany
	 */
	public function schedules()
	{
		return $this->hasMany(
			// Model
			'App\Models\Schedule',
			// Foreign key
			'lecturer_id',
			// Local key
			'id'
		);
	}



}
